<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Application\" />
  </ItemGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.13" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.13" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared.Kernel\Shared.Kernel.csproj" />
  </ItemGroup>

</Project>
